export type BodyKind = "star" | "planet" | "dwarf" | "moon" | "ring";

export interface BodyDefinition {
  id: string;
  name: string;
  kind: BodyKind;
  parentId: string | null;
  radiusKm: number;
  distanceAu: number;
  orbitalPeriodDays: number;
  rotationPeriodHours: number;
  axialTiltDeg: number;
  orbitInclinationDeg: number;
  /** J2000 Keplerian elements for heliocentric bodies. */
  eccentricity?: number;
  longitudeOfAscendingNodeDeg?: number;
  argumentOfPerihelionDeg?: number;
  meanAnomalyAtEpochDeg?: number;
  /** Circular-orbit phase for moons. */
  epochLongitudeDeg: number;
  texture?: string;
  atmosphereTexture?: string;
  ringTexture?: string;
  color?: string;
  focusable: boolean;
}

/** Scene distances use compressed AU; sizes use Earth radius = 1 unit. */
export const BODIES: BodyDefinition[] = [
  {
    id: "sun",
    name: "Sun",
    kind: "star",
    parentId: null,
    radiusKm: 696_000,
    distanceAu: 0,
    orbitalPeriodDays: 1,
    rotationPeriodHours: 609,
    axialTiltDeg: 7.25,
    orbitInclinationDeg: 0,
    epochLongitudeDeg: 0,
    texture: "/textures/sun.jpg",
    focusable: true,
  },
  {
    id: "mercury",
    name: "Mercury",
    kind: "planet",
    parentId: "sun",
    radiusKm: 2_440,
    distanceAu: 0.387,
    orbitalPeriodDays: 87.97,
    rotationPeriodHours: 1407.6,
    axialTiltDeg: 0.034,
    orbitInclinationDeg: 7.005,
    eccentricity: 0.2056,
    longitudeOfAscendingNodeDeg: 48.331,
    argumentOfPerihelionDeg: 29.124,
    meanAnomalyAtEpochDeg: 174.796,
    epochLongitudeDeg: 0,
    texture: "/textures/mercury.jpg",
    focusable: true,
  },
  {
    id: "venus",
    name: "Venus",
    kind: "planet",
    parentId: "sun",
    radiusKm: 6_052,
    distanceAu: 0.723,
    orbitalPeriodDays: 224.7,
    rotationPeriodHours: -5832.5,
    axialTiltDeg: 177.4,
    orbitInclinationDeg: 3.395,
    eccentricity: 0.00677,
    longitudeOfAscendingNodeDeg: 76.68,
    argumentOfPerihelionDeg: 54.884,
    meanAnomalyAtEpochDeg: 50.115,
    epochLongitudeDeg: 0,
    texture: "/textures/venus.jpg",
    focusable: true,
  },
  {
    id: "earth",
    name: "Earth",
    kind: "planet",
    parentId: "sun",
    radiusKm: 6_371,
    distanceAu: 1,
    orbitalPeriodDays: 365.25,
    rotationPeriodHours: 24,
    axialTiltDeg: 23.44,
    orbitInclinationDeg: 0.00005,
    eccentricity: 0.0167,
    longitudeOfAscendingNodeDeg: -11.261,
    argumentOfPerihelionDeg: 114.208,
    meanAnomalyAtEpochDeg: 358.617,
    epochLongitudeDeg: 0,
    texture: "/textures/earth.jpg",
    focusable: true,
  },
  {
    id: "moon",
    name: "Moon",
    kind: "moon",
    parentId: "earth",
    radiusKm: 1_737,
    distanceAu: 0.00257,
    orbitalPeriodDays: 27.32,
    rotationPeriodHours: 655.7,
    axialTiltDeg: 6.68,
    orbitInclinationDeg: 5.15,
    epochLongitudeDeg: 90,
    texture: "/textures/moon.jpg",
    focusable: true,
  },
  {
    id: "mars",
    name: "Mars",
    kind: "planet",
    parentId: "sun",
    radiusKm: 3_390,
    distanceAu: 1.524,
    orbitalPeriodDays: 686.98,
    rotationPeriodHours: 24.6,
    axialTiltDeg: 25.19,
    orbitInclinationDeg: 1.85,
    eccentricity: 0.0934,
    longitudeOfAscendingNodeDeg: 49.558,
    argumentOfPerihelionDeg: 286.502,
    meanAnomalyAtEpochDeg: 18.602,
    epochLongitudeDeg: 0,
    texture: "/textures/mars.jpg",
    focusable: true,
  },
  {
    id: "jupiter",
    name: "Jupiter",
    kind: "planet",
    parentId: "sun",
    radiusKm: 69_911,
    distanceAu: 5.203,
    orbitalPeriodDays: 4332.59,
    rotationPeriodHours: 9.9,
    axialTiltDeg: 3.13,
    orbitInclinationDeg: 1.303,
    eccentricity: 0.0485,
    longitudeOfAscendingNodeDeg: 100.464,
    argumentOfPerihelionDeg: 273.867,
    meanAnomalyAtEpochDeg: 19.65,
    epochLongitudeDeg: 0,
    texture: "/textures/jupiter.jpg",
    focusable: true,
  },
  {
    id: "io",
    name: "Io",
    kind: "moon",
    parentId: "jupiter",
    radiusKm: 1_821,
    distanceAu: 0.00282,
    orbitalPeriodDays: 1.77,
    rotationPeriodHours: 42.5,
    axialTiltDeg: 0,
    orbitInclinationDeg: 0,
    epochLongitudeDeg: 30,
    texture: "/textures/io.jpg",
    focusable: false,
  },
  {
    id: "europa",
    name: "Europa",
    kind: "moon",
    parentId: "jupiter",
    radiusKm: 1_560,
    distanceAu: 0.00448,
    orbitalPeriodDays: 3.55,
    rotationPeriodHours: 85.2,
    axialTiltDeg: 0,
    orbitInclinationDeg: 0,
    epochLongitudeDeg: 150,
    texture: "/textures/europa.jpg",
    focusable: false,
  },
  {
    id: "ganymede",
    name: "Ganymede",
    kind: "moon",
    parentId: "jupiter",
    radiusKm: 2_634,
    distanceAu: 0.00716,
    orbitalPeriodDays: 7.15,
    rotationPeriodHours: 171.6,
    axialTiltDeg: 0,
    orbitInclinationDeg: 0,
    epochLongitudeDeg: 250,
    texture: "/textures/ganymede.jpg",
    focusable: false,
  },
  {
    id: "callisto",
    name: "Callisto",
    kind: "moon",
    parentId: "jupiter",
    radiusKm: 2_410,
    distanceAu: 0.01259,
    orbitalPeriodDays: 16.69,
    rotationPeriodHours: 400.6,
    axialTiltDeg: 0,
    orbitInclinationDeg: 0,
    epochLongitudeDeg: 60,
    texture: "/textures/callisto.jpg",
    focusable: false,
  },
  {
    id: "saturn",
    name: "Saturn",
    kind: "planet",
    parentId: "sun",
    radiusKm: 58_232,
    distanceAu: 9.537,
    orbitalPeriodDays: 10_759,
    rotationPeriodHours: 10.7,
    axialTiltDeg: 26.73,
    orbitInclinationDeg: 2.489,
    eccentricity: 0.0545,
    longitudeOfAscendingNodeDeg: 113.665,
    argumentOfPerihelionDeg: 339.392,
    meanAnomalyAtEpochDeg: 317.02,
    epochLongitudeDeg: 0,
    texture: "/textures/saturn.jpg",
    ringTexture: "/textures/saturn-ring.png",
    focusable: true,
  },
  {
    id: "titan",
    name: "Titan",
    kind: "moon",
    parentId: "saturn",
    radiusKm: 2_575,
    distanceAu: 0.00817,
    orbitalPeriodDays: 15.95,
    rotationPeriodHours: 382.8,
    axialTiltDeg: 0,
    orbitInclinationDeg: 0,
    epochLongitudeDeg: 200,
    texture: "/textures/titan.webp",
    focusable: false,
  },
  {
    id: "uranus",
    name: "Uranus",
    kind: "planet",
    parentId: "sun",
    radiusKm: 25_362,
    distanceAu: 19.19,
    orbitalPeriodDays: 30_687,
    rotationPeriodHours: 17.2,
    axialTiltDeg: 97.77,
    orbitInclinationDeg: 0.773,
    eccentricity: 0.0473,
    longitudeOfAscendingNodeDeg: 74.006,
    argumentOfPerihelionDeg: 96.998,
    meanAnomalyAtEpochDeg: 142.955,
    epochLongitudeDeg: 0,
    texture: "/textures/uranus.jpg",
    focusable: true,
  },
  {
    id: "neptune",
    name: "Neptune",
    kind: "planet",
    parentId: "sun",
    radiusKm: 24_622,
    distanceAu: 30.07,
    orbitalPeriodDays: 60_190,
    rotationPeriodHours: 16.1,
    axialTiltDeg: 28.32,
    orbitInclinationDeg: 1.77,
    eccentricity: 0.0086,
    longitudeOfAscendingNodeDeg: 131.784,
    argumentOfPerihelionDeg: 276.336,
    meanAnomalyAtEpochDeg: 256.228,
    epochLongitudeDeg: 0,
    texture: "/textures/neptune.jpg",
    focusable: true,
  },
  {
    id: "triton",
    name: "Triton",
    kind: "moon",
    parentId: "neptune",
    radiusKm: 1_353,
    distanceAu: 0.00237,
    orbitalPeriodDays: 5.88,
    rotationPeriodHours: 141.1,
    axialTiltDeg: 0,
    orbitInclinationDeg: 157,
    epochLongitudeDeg: 120,
    texture: "/textures/triton.jpg",
    focusable: false,
  },
  {
    id: "pluto",
    name: "Pluto",
    kind: "dwarf",
    parentId: "sun",
    radiusKm: 1_188,
    distanceAu: 39.48,
    orbitalPeriodDays: 90_560,
    rotationPeriodHours: 153.3,
    axialTiltDeg: 122.5,
    orbitInclinationDeg: 17.14,
    eccentricity: 0.2488,
    longitudeOfAscendingNodeDeg: 110.303,
    argumentOfPerihelionDeg: 113.763,
    meanAnomalyAtEpochDeg: 14.53,
    epochLongitudeDeg: 0,
    texture: "/textures/pluto.jpg",
    color: "#c9a882",
    focusable: true,
  },
];

export const BODY_BY_ID = Object.fromEntries(
  BODIES.map((body) => [body.id, body]),
) as Record<string, BodyDefinition>;

/** Planet picker order — Moon sits directly after Earth. */
export const PICKER_BODY_IDS = [
  "sun",
  "mercury",
  "venus",
  "earth",
  "moon",
  "mars",
  "jupiter",
  "saturn",
  "uranus",
  "neptune",
  "pluto",
] as const;

export const PICKER_BODIES = PICKER_BODY_IDS.map((id) => BODY_BY_ID[id]);

export const DEFAULT_FOCUS_ID = "earth";